services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "10000:10000"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    stdin_open: true
    tty: true
    environment:
      - ICE_HOST=server
