import csv
import random

webinar_names = [
    "Introduction to Python",
    "Advanced Excel Techniques",
    "Mastering Public Speaking",
    "Digital Marketing Basics",
    "Graphic Design for Beginners",
    "SEO Strategies for 2025",
    "Building Your First Website",
    "Data Analysis with R",
    "AI and Machine Learning Fundamentals",
    "Cybersecurity Essentials",
    "Project Management 101",
    "Social Media Marketing Tips",
    "Investing for Beginners",
    "Creating a Winning Resume",
    "Intro to Cryptocurrency",
    "Time Management Hacks",
    "Building Mobile Apps",
    "Content Writing Secrets",
    "Financial Planning Basics",
    "Photography Tips and Tricks",
    "Video Editing with Premiere Pro",
    "Basics of Blockchain",
    "Understanding Cloud Computing",
    "Introduction to JavaScript",
    "Email Marketing Strategies",
    "How to Start a Podcast",
    "Excel for Data Analysis",
    "Leadership Skills Development",
    "Python for Data Science",
    "Freelancing Made Easy",
    "3D Modeling Basics",
    "Customer Service Excellence",
    "Career Growth Strategies",
    "Machine Learning with Python",
    "Basic HTML and CSS",
    "Event Planning 101",
    "Cooking Healthy Meals",
    "Self-Care and Wellness",
    "Personal Branding Mastery",
    "Digital Illustration for Beginners",
    "SQL for Beginners",
    "Mobile App Marketing",
    "Video Marketing Techniques",
    "Game Development Basics",
    "Social Media Growth Hacks",
    "Networking for Success",
    "Building E-commerce Websites",
    "Freelance Writing 101",
    "Creative Problem Solving",
    "Artificial Intelligence Trends",
    "Productivity Tools Overview",
    "Ethical Hacking Basics",
    "Virtual Reality in Business",
    "Marketing Analytics Explained",
    "Writing Effective Proposals",
    "Music Production Fundamentals",
    "Basics of Business Law",
    "Mindfulness and Meditation",
    "Online Business Essentials",
    "Stock Market Basics",
    "Introduction to Data Mining",
    "Building a Personal Website",
    "Video Storytelling Tips",
    "Fitness for Beginners",
    "Interior Design Basics",
    "Starting a YouTube Channel",
    "Improving Communication Skills",
    "Fundamentals of Programming",
    "Financial Independence Guide",
    "Art Therapy Workshop",
    "How to Write a Book",
    "Personal Finance Management",
    "Healthy Lifestyle Tips",
    "Understanding NFTs",
    "Career Transition Strategies",
    "Copywriting Essentials",
    "Building a Strong Portfolio",
    "Introduction to Robotics",
    "Time-saving Tech Tools",
    "Basics of Virtual Teams",
    "Public Relations 101",
    "Augmented Reality Explained",
    "SEO for E-commerce",
    "Mobile Photography Tips",
    "Ethical Business Practices",
    "Basics of Animation",
    "How to Build a Startup",
    "Exploring Digital Art",
    "Introduction to UX/UI Design",
    "Fundamentals of Agile",
    "Storytelling for Marketers",
    "PowerPoint Presentation Tips",
    "Customer Retention Strategies",
    "Affiliate Marketing Guide",
    "Introduction to React.js",
    "Leadership for Women",
    "Exploring Cultural Diversity",
    "How to Start an Online Store",
    "Introduction to Virtual Events",
    "Podcast Monetization Tips",
    "Career Change Advice",
    "Strategic Thinking Workshop",
    "Business Writing Skills",
    "Negotiation Skills Training",
    "Emotional Intelligence Workshop",
    "Introduction to Laravel",
    "How to Create Viral Content",
    "Social Media Trends for 2025",
    "Boosting Workplace Productivity",
    "Creative Writing Basics",
    "Ethics in Technology",
    "Introduction to E-learning",
    "Building Better Habits",
    "Fundamentals of Marketing",
    "Introduction to Kotlin",
    "Effective Goal Setting",
    "How to Start a Blog",
    "Digital Art Techniques",
    "Stress Management Workshop",
    "Introduction to Node.js",
    "Gamification in Business",
    "Basic Python Scripting",
    "Freelance Marketing Tips",
    "Virtual Team Collaboration",
    "Introduction to Big Data",
    "Basics of Game Design",
    "Business Strategy Basics",
    "Cloud Security Essentials",
    "Modern JavaScript Techniques",
    "Basics of PHP Programming",
    "Fundamentals of Coaching",
    "How to Build a Side Hustle",
    "How to Conduct Webinars",
    "Basics of Fashion Design",
    "Advanced Photoshop Tricks",
    "Introduction to API Design",
    "Digital Strategy for Startups",
    "Introduction to Figma",
    "Personal Productivity Hacks",
    "Exploring IoT Applications",
    "The Art of Negotiation",
    "Introduction to Swift",
    "Work-life Balance Tips",
    "Business Analytics Fundamentals",
    "Understanding SaaS",
    "Basics of Digital Storytelling",
    "Building Your LinkedIn Profile",
    "Product Management Basics",
    "How to Run a Non-profit",
    "Understanding E-commerce",
    "How to Write Press Releases",
    "The Future of AI",
    "Mastering Remote Work",
    "Building Cross-functional Teams",
    "Introduction to Python Django",
    "Basics of Cyberlaw",
    "E-mail Automation Basics",
    "How to Create E-books",
    "Marketing on TikTok",
    "Creating Viral Videos",
    "Digital Transformation Explained",
    "Basics of Scrum",
    "How to Start a Dropshipping Business",
    "Virtual Networking Tips",
    "The Art of Journaling",
    "Exploring Minimalism",
    "The Science of Happiness",
    "Introduction to Kotlin for Android",
    "Basics of Data Visualization",
    "Understanding Risk Management",
    "Basics of Quantum Computing",
    "How to Create Better Surveys",
    "Introduction to Personal Finance",
    "Basic Yoga Practices",
    "Freelance Graphic Design Tips",
    "Introduction to Machine Learning Libraries",
    "Basics of Content Marketing",
    "Introduction to Ethical Hacking",
    "How to Use Google Analytics",
    "Basics of Web Hosting",
    "Introduction to App Development",
    "Career Development Hacks",
    "The Future of Marketing",
    "How to Start a Career in Tech",
    "Basics of Product Launches",
    "Mastering Customer Feedback",
    "Introduction to Android Development"
]

webinars_dec = [
    {"name": "Introduction to Python", "description": "Learn Python basics for beginners."},
    {"name": "Advanced Excel Techniques", "description": "Master advanced Excel tools and formulas."},
    {"name": "Mastering Public Speaking", "description": "Improve your public speaking confidence."},
    {"name": "Digital Marketing Basics", "description": "Understand key digital marketing strategies."},
    {"name": "Graphic Design for Beginners", "description": "Explore basic graphic design concepts."},
    {"name": "SEO Strategies for 2025", "description": "Learn the latest SEO tips for success."},
    {"name": "Building Your First Website", "description": "Step-by-step guide to building websites."},
    {"name": "Data Analysis with R", "description": "Analyze data effectively using R."},
    {"name": "AI and Machine Learning Fundamentals", "description": "Introduction to AI and ML basics."},
    {"name": "Cybersecurity Essentials", "description": "Learn to protect data from cyber threats."},
    {"name": "Project Management 101", "description": "Basics of managing projects successfully."},
    {"name": "Social Media Marketing Tips", "description": "Boost engagement on social platforms."},
    {"name": "Investing for Beginners", "description": "Understand the basics of investing."},
    {"name": "Creating a Winning Resume", "description": "Build resumes that stand out."},
    {"name": "Intro to Cryptocurrency", "description": "Learn cryptocurrency fundamentals."},
    {"name": "Time Management Hacks", "description": "Improve productivity with time hacks."},
    {"name": "Building Mobile Apps", "description": "Create mobile apps step-by-step."},
    {"name": "Content Writing Secrets", "description": "Master the art of content writing."},
    {"name": "Financial Planning Basics", "description": "Plan your finances effectively."},
    {"name": "Photography Tips and Tricks", "description": "Enhance your photography skills."},
    {"name": "Video Editing with Premiere Pro", "description": "Edit videos professionally."},
    {"name": "Basics of Blockchain", "description": "Understand how blockchain works."},
    {"name": "Understanding Cloud Computing", "description": "Explore cloud computing basics."},
    {"name": "Introduction to JavaScript", "description": "Learn the essentials of JavaScript."},
    {"name": "Email Marketing Strategies", "description": "Create effective email campaigns."},
    {"name": "How to Start a Podcast", "description": "Launch and grow your podcast."},
    {"name": "Excel for Data Analysis", "description": "Discover how to use Excel to analyze and visualize data effectively. Learn formulas, charts, and tools to streamline your workflow."},
    {"name": "Leadership Skills Development", "description": "Enhance your ability to lead and inspire teams. Understand key strategies for effective decision-making and communication."},
    {"name": "Python for Data Science", "description": "Dive into Python for analyzing and visualizing data. Explore libraries like Pandas, NumPy, and Matplotlib to solve real-world problems."},
    {"name": "Freelancing Made Easy", "description": "Learn the secrets of building a successful freelance career. Discover tips for finding clients and managing your workload."},
    {"name": "3D Modeling Basics", "description": "Get started with creating 3D models using popular software. Understand key concepts like rendering, texturing, and object design."},
    {"name": "Customer Service Excellence", "description": "Master the art of delivering exceptional customer service. Learn strategies for handling difficult situations with professionalism."},
    {"name": "Career Growth Strategies", "description": "Plan your career trajectory with actionable strategies. Discover tips for skill development and networking effectively."},
    {"name": "Machine Learning with Python", "description": "Explore machine learning concepts using Python. Learn to build predictive models with libraries like scikit-learn."},
    {"name": "Basic HTML and CSS", "description": "Learn the fundamentals of building websites with HTML and CSS. Create structured and visually appealing web pages from scratch."},
    {"name": "Event Planning 101", "description": "Discover the essentials of organizing successful events. Learn budgeting, scheduling, and managing logistics."},
    {"name": "Cooking Healthy Meals", "description": "Explore recipes and techniques for preparing nutritious meals. Learn how to balance flavors and maintain a healthy diet."},
    {"name": "Self-Care and Wellness", "description": "Prioritize your well-being with self-care techniques. Discover strategies for managing stress and maintaining mental health."},
    {"name": "Personal Branding Mastery", "description": "Build a strong personal brand that sets you apart. Learn how to present your skills and create a lasting impression."},
    {"name": "Digital Illustration for Beginners", "description": "Start your journey in digital art with fundamental techniques. Learn to use popular tools to bring your ideas to life."},
    {"name": "SQL for Beginners", "description": "Understand the basics of SQL for managing databases. Learn to write queries to retrieve and manipulate data efficiently."},
    {"name": "Mobile App Marketing", "description": "Discover strategies to promote and grow your mobile app. Learn techniques for user acquisition and retention."},
    {"name": "Video Marketing Techniques", "description": "Leverage videos to boost your marketing efforts. Learn to create engaging content that resonates with your audience."},
    {"name": "Game Development Basics", "description": "Explore the fundamentals of creating your own games. Understand key concepts like design, programming, and prototyping."},
    {"name": "Social Media Growth Hacks", "description": "Learn strategies to rapidly grow your social media presence. Discover techniques to increase engagement and attract followers."},
    {"name": "Networking for Success", "description": "Master the art of building meaningful professional connections. Learn effective networking strategies for both in-person and online settings."},
    {"name": "Building E-commerce Websites", "description": "Understand how to create and manage an e-commerce site. Learn about platforms, payment systems, and design tips to enhance user experience."},
    {"name": "Freelance Writing 101", "description": "Explore the essentials of starting a career in freelance writing. Learn how to find clients, pitch ideas, and deliver quality work."},
    {"name": "Creative Problem Solving", "description": "Develop innovative approaches to tackle challenges effectively. Learn techniques to think outside the box and find unique solutions."},
    {"name": "Artificial Intelligence Trends", "description": "Stay updated on the latest trends in AI and their applications. Explore how AI is transforming industries and creating new opportunities."},
    {"name": "Productivity Tools Overview", "description": "Discover the best tools to improve your productivity at work and home. Learn how to integrate these tools into your daily routines for maximum efficiency."},
    {"name": "Ethical Hacking Basics", "description": "Learn how to identify and fix vulnerabilities in systems. Gain a foundation in cybersecurity practices and ethical hacking principles."},
    {"name": "Virtual Reality in Business", "description": "Explore the applications of virtual reality in various industries. Learn how VR can enhance training, marketing, and customer experiences."},
    {"name": "Marketing Analytics Explained", "description": "Understand the basics of analyzing marketing data. Learn how to measure campaign success and make data-driven decisions."},
    {"name": "Writing Effective Proposals", "description": "Master the art of crafting compelling business proposals. Learn to communicate your ideas clearly and win client approval."},
    {"name": "Music Production Fundamentals", "description": "Discover the basics of producing music using digital tools. Learn about mixing, editing, and creating tracks from scratch."},
    {"name": "Basics of Business Law", "description": "Understand the foundational concepts of business law. Learn about contracts, intellectual property, and compliance essentials."},
    {"name": "Mindfulness and Meditation", "description": "Develop techniques to stay present and focused in daily life. Explore meditation practices that improve mental clarity and well-being."},
    {"name": "Online Business Essentials", "description": "Learn the key steps to starting and managing an online business. Understand digital tools and strategies to grow your brand."},
    {"name": "Stock Market Basics", "description": "Get introduced to the fundamentals of stock market investing. Learn about stocks, trading strategies, and managing risk."},
    {"name": "Introduction to Data Mining", "description": "Discover how to extract meaningful insights from large datasets. Learn the basics of algorithms and tools used in data mining."},
    {"name": "Building a Personal Website", "description": "Create a website to showcase your skills and portfolio. Learn the basics of design, hosting, and personal branding."},
    {"name": "Video Storytelling Tips", "description": "Learn how to create compelling stories through video. Explore techniques for scripting, filming, and editing engaging content."},
    {"name": "Fitness for Beginners", "description": "Start your fitness journey with simple exercises and tips. Learn how to build a routine that works for your lifestyle."},
    {"name": "Interior Design Basics", "description": "Explore the fundamentals of creating beautiful and functional spaces. Learn about color theory, furniture layout, and design principles."},
    {"name": "Starting a YouTube Channel", "description": "Learn the steps to launch and grow your YouTube channel. Discover tips for creating engaging content and reaching your audience."},
    {"name": "Improving Communication Skills", "description": "Enhance your ability to communicate effectively in any setting. Learn strategies for active listening and clear expression."},
    {"name": "Fundamentals of Programming", "description": "Understand the basics of coding and programming logic. Learn how to write simple programs in popular languages."},
    {"name": "Financial Independence Guide", "description": "Plan your path to achieving financial independence. Learn strategies for saving, investing, and managing money wisely."},
    {"name": "Art Therapy Workshop",
     "description": "Discover the healing power of art through guided creative exercises. Learn how art can enhance emotional well-being and reduce stress."},
    {"name": "How to Write a Book",
     "description": "Explore the steps to turning your ideas into a compelling manuscript. Learn about outlining, drafting, and editing your book."},
    {"name": "Personal Finance Management",
     "description": "Master the basics of budgeting, saving, and managing debt. Learn strategies to achieve financial stability and grow your wealth."},
    {"name": "Healthy Lifestyle Tips",
     "description": "Discover practical tips for improving your physical and mental health. Learn how to create sustainable habits for a balanced life."},
    {"name": "Understanding NFTs",
     "description": "Learn the basics of non-fungible tokens and their applications. Explore how NFTs are transforming art, gaming, and ownership."},
    {"name": "Career Transition Strategies",
     "description": "Navigate career changes with confidence and clarity. Learn how to identify your strengths and position yourself for new opportunities."},
    {"name": "Copywriting Essentials",
     "description": "Master the art of writing persuasive and engaging copy. Learn techniques to captivate your audience and drive action."},
    {"name": "Building a Strong Portfolio",
     "description": "Create a portfolio that highlights your skills and accomplishments. Learn how to organize your work to impress potential clients or employers."},
    {"name": "Introduction to Robotics",
     "description": "Dive into the fundamentals of robotics and automation. Learn about sensors, actuators, and the basics of robot programming."},
    {"name": "Time-saving Tech Tools",
     "description": "Discover tools that can help you automate tasks and save time. Learn how to integrate them seamlessly into your daily workflows."},
    {"name": "Basics of Virtual Teams",
     "description": "Understand the dynamics of managing and working in virtual teams. Learn strategies to enhance communication and collaboration online."},
    {"name": "Public Relations 101",
     "description": "Explore the fundamentals of building and maintaining a positive public image. Learn effective strategies for managing media and stakeholder relationships."},
    {"name": "Augmented Reality Explained",
     "description": "Understand how augmented reality works and its practical applications. Explore how AR is changing industries like gaming, marketing, and education."},
    {"name": "SEO for E-commerce",
     "description": "Learn SEO strategies tailored for e-commerce platforms. Discover techniques to boost your online store's visibility and traffic."},
    {"name": "Mobile Photography Tips",
     "description": "Enhance your mobile photography skills with simple tricks. Learn how to compose, edit, and capture stunning shots with your phone."},
    {"name": "Ethical Business Practices",
     "description": "Explore the importance of ethics in business decision-making. Learn how to build trust and integrity within your organization."},
    {"name": "Basics of Animation",
     "description": "Get started with animation by learning fundamental techniques. Explore tools and workflows to create dynamic animated content."},
    {"name": "How to Build a Startup",
     "description": "Learn the key steps to turning your idea into a successful startup. Understand funding, business planning, and market validation."},
    {"name": "Exploring Digital Art",
     "description": "Dive into the world of digital art with beginner-friendly tools. Learn techniques to create stunning artworks using tablets and software."},
    {"name": "Introduction to UX/UI Design",
     "description": "Understand the principles of designing user-friendly interfaces. Learn how to enhance user experiences with practical design tips."},
    {"name": "Fundamentals of Agile",
     "description": "Discover the core principles of Agile project management. Learn how to improve team collaboration and deliver results faster."},
    {"name": "Storytelling for Marketers",
     "description": "Learn how to use storytelling to engage and inspire your audience. Discover techniques to create memorable brand narratives."},
    {"name": "PowerPoint Presentation Tips",
     "description": "Enhance your presentation skills with advanced PowerPoint tips. Learn how to design slides that are visually appealing and impactful."},
    {"name": "Customer Retention Strategies",
     "description": "Explore ways to keep your customers loyal and engaged. Learn techniques to build strong relationships and increase retention rates."},
    {"name": "Affiliate Marketing Guide",
     "description": "Learn the fundamentals of affiliate marketing and how to get started. Discover the best strategies to generate passive income through affiliate partnerships."},
    {"name": "Introduction to React.js",
     "description": "Explore the basics of React.js and how it simplifies building interactive user interfaces. Learn about components, state management, and hooks."},
    {"name": "Leadership for Women",
     "description": "Empower yourself with leadership skills designed for women. Learn strategies for overcoming challenges and leading with confidence in any setting."},
    {"name": "Exploring Cultural Diversity",
     "description": "Understand the importance of cultural diversity in today's world. Learn how to foster inclusivity and respect for diverse perspectives in professional and personal environments."},
    {"name": "How to Start an Online Store",
     "description": "Learn how to launch a successful online store from scratch. Understand e-commerce platforms, product selection, and marketing strategies."},
    {"name": "Introduction to Virtual Events",
     "description": "Get started with organizing virtual events that engage and inspire. Learn the tools and strategies to host webinars, conferences, and live events online."},
    {"name": "Podcast Monetization Tips",
     "description": "Discover how to monetize your podcast effectively. Learn about sponsorships, ads, and other revenue-generating strategies."},
    {"name": "Career Change Advice",
     "description": "Navigate the process of changing careers with expert advice. Learn how to leverage your skills and network to transition smoothly into a new field."},
    {"name": "Strategic Thinking Workshop",
     "description": "Develop the ability to think strategically and make informed decisions. Learn frameworks and tools to tackle complex problems and drive business success."},
    {"name": "Business Writing Skills",
     "description": "Master the art of business writing for clear and professional communication. Learn how to write reports, emails, proposals, and more."},
    {"name": "Negotiation Skills Training",
     "description": "Enhance your negotiation skills to achieve better outcomes. Learn key techniques for handling negotiations in both business and personal settings."},
    {"name": "Emotional Intelligence Workshop",
     "description": "Discover the power of emotional intelligence in leadership and relationships. Learn how to manage emotions, empathize with others, and improve communication."},
    {"name": "Introduction to Laravel",
     "description": "Explore the fundamentals of Laravel, a powerful PHP framework. Learn how to build web applications efficiently using MVC architecture."},
    {"name": "How to Create Viral Content",
     "description": "Learn the strategies behind creating content that resonates and spreads rapidly. Discover tips on creating shareable, engaging posts for any platform."},
    {"name": "Social Media Trends for 2025",
     "description": "Stay ahead of the curve by understanding upcoming social media trends. Learn how to adapt your marketing strategies to align with the future of digital platforms."},
    {"name": "Boosting Workplace Productivity",
     "description": "Increase productivity at work with effective time management and organizational techniques. Learn how to overcome distractions and stay focused on key tasks."},
    {"name": "Creative Writing Basics",
     "description": "Unlock your creative potential with foundational writing techniques. Learn how to craft engaging stories, characters, and plots."},
    {"name": "Ethics in Technology",
     "description": "Understand the ethical implications of technology in modern society. Explore topics like data privacy, AI ethics, and the responsibility of tech creators."},
    {"name": "Introduction to E-learning",
     "description": "Explore the world of e-learning and how it’s transforming education. Learn how to create engaging online courses and deliver effective learning experiences."},
    {"name": "Building Better Habits",
     "description": "Learn how to create and sustain positive habits that lead to personal growth. Discover strategies to break bad habits and build a routine that sticks."},
    {"name": "Fundamentals of Marketing",
     "description": "Understand the core principles of marketing and how to apply them. Learn about market research, branding, and creating successful marketing strategies."},
    {"name": "Introduction to Kotlin",
     "description": "Get started with Kotlin, the modern programming language for Android development. Learn basic syntax, data structures, and object-oriented principles."},
    {"name": "Effective Goal Setting",
     "description": "Learn how to set and achieve meaningful goals. Discover strategies to stay focused, measure progress, and stay motivated."},
    {"name": "How to Start a Blog",
     "description": "Learn the steps to create a blog that attracts readers and generates revenue. Discover tips on content creation, SEO, and monetization strategies."},
    {"name": "Digital Art Techniques",
     "description": "Learn advanced techniques for creating stunning digital art. Explore various tools and styles to enhance your creativity and skills."},
    {"name": "Stress Management Workshop",
     "description": "Discover strategies to manage and reduce stress in both personal and professional settings. Learn relaxation techniques and how to maintain mental well-being."},
    {"name": "Introduction to Node.js",
     "description": "Get started with Node.js, a powerful JavaScript runtime. Learn how to build scalable server-side applications with ease."},
    {"name": "Gamification in Business",
     "description": "Understand how to use gamification to engage employees and customers. Learn techniques for applying game mechanics to business processes."},
    {"name": "Basic Python Scripting",
     "description": "Learn the fundamentals of Python programming for automation and scripting. Discover how to write simple scripts to solve real-world problems."},
    {"name": "Freelance Marketing Tips",
     "description": "Master marketing strategies to attract clients as a freelancer. Learn how to build a personal brand, network, and promote your services effectively."},
    {"name": "Virtual Team Collaboration",
     "description": "Learn how to collaborate effectively with virtual teams. Discover tools and techniques to improve communication, productivity, and team cohesion."},
    {"name": "Introduction to Big Data",
     "description": "Explore the world of big data and how to harness its power for decision-making. Learn about data processing, analysis, and visualization techniques."},
    {"name": "Basics of Game Design",
     "description": "Learn the fundamental principles of game design. Explore how to create engaging mechanics, storylines, and characters for your own games."},
    {"name": "Business Strategy Basics",
     "description": "Understand the core concepts of business strategy. Learn how to develop long-term goals and align them with your company's resources and capabilities."},
    {"name": "Cloud Security Essentials",
     "description": "Learn the essentials of securing data and applications in the cloud. Understand key principles of cloud security and how to protect sensitive information."},
    {"name": "Modern JavaScript Techniques",
     "description": "Master modern JavaScript features and best practices. Learn how to write clean, efficient, and scalable code for web development."},
    {"name": "Basics of PHP Programming",
     "description": "Get started with PHP, one of the most popular server-side languages. Learn how to create dynamic websites and web applications using PHP."},
    {"name": "Fundamentals of Coaching",
     "description": "Discover the core principles of coaching and how to apply them effectively. Learn how to help others reach their goals through guidance and support."},
    {"name": "How to Build a Side Hustle",
     "description": "Learn how to start and grow a side business alongside your full-time job. Explore strategies for time management, marketing, and monetization."},
    {"name": "How to Conduct Webinars",
     "description": "Master the art of hosting successful webinars. Learn how to engage your audience, present effectively, and use webinar tools to your advantage."},
    {"name": "Basics of Fashion Design",
     "description": "Learn the fundamentals of fashion design, from concept to creation. Explore how to sketch, choose fabrics, and bring your designs to life."},
    {"name": "Advanced Photoshop Tricks",
     "description": "Take your Photoshop skills to the next level with advanced tips and techniques. Learn how to create professional-quality images and graphics."},
    {"name": "Introduction to API Design",
     "description": "Understand the principles of API design and development. Learn how to create efficient, scalable, and secure APIs for your applications."},
    {"name": "Digital Strategy for Startups",
     "description": "Learn how to develop and execute a digital strategy for your startup. Explore the best digital marketing, branding, and growth tactics."},
    {"name": "Introduction to Figma",
     "description": "Get started with Figma, the popular design and prototyping tool. Learn how to create user-friendly interfaces and collaborate with teams in real time."},
    {"name": "Personal Productivity Hacks",
     "description": "Boost your productivity with simple and effective time management techniques. Learn how to focus on high-priority tasks and eliminate distractions."},
    {"name": "Exploring IoT Applications",
     "description": "Discover the potential of the Internet of Things (IoT) and its wide range of applications. Learn how IoT is transforming industries like healthcare, manufacturing, and home automation."},
    {"name": "The Art of Negotiation",
     "description": "Master the skills needed to negotiate effectively in any situation. Learn how to handle difficult conversations and reach mutually beneficial agreements."},
    {"name": "Introduction to Swift",
     "description": "Get started with Swift, Apple's programming language for iOS and macOS apps. Learn the fundamentals of Swift syntax, design patterns, and app development."},
    {"name": "Work-life Balance Tips",
     "description": "Learn how to achieve a healthy work-life balance. Discover strategies to manage your time, set boundaries, and prioritize well-being."},
    {"name": "Business Analytics Fundamentals",
     "description": "Understand the key concepts of business analytics and how to apply them. Learn how to analyze data and use insights to drive business decisions."},
    {"name": "Understanding SaaS",
     "description": "Explore the world of Software as a Service (SaaS) and its impact on business operations. Learn how SaaS products are delivered, used, and scaled."},
    {"name": "Basics of Digital Storytelling",
     "description": "Learn how to create compelling stories using digital media. Explore the basics of writing, editing, and presenting stories across various platforms."},
    {"name": "Building Your LinkedIn Profile",
     "description": "Enhance your LinkedIn profile to attract employers and clients. Learn how to showcase your skills, experience, and professional accomplishments."},
    {"name": "Product Management Basics",
     "description": "Understand the essential principles of product management. Learn how to develop, launch, and manage products that meet customer needs."},
    {"name": "How to Run a Non-profit",
     "description": "Learn how to start and manage a successful non-profit organization. Understand the basics of fundraising, leadership, and organizational growth."},
    {"name": "Understanding E-commerce",
     "description": "Explore the fundamentals of e-commerce and online business models. Learn how to set up and manage an e-commerce site for maximum success."},
    {"name": "How to Write Press Releases",
     "description": "Learn the art of writing effective press releases that grab attention. Discover the key elements of a press release and how to get media coverage."},
    {"name": "The Future of AI",
     "description": "Explore the evolving landscape of artificial intelligence and its future implications. Learn about upcoming trends and how AI will impact various industries."},
    {"name": "Mastering Remote Work",
     "description": "Master the skills needed to thrive in a remote work environment. Learn strategies for staying productive, managing teams, and maintaining work-life balance."},
    {"name": "Building Cross-functional Teams",
     "description": "Learn how to build and manage teams with diverse skill sets. Understand the importance of cross-functional collaboration to achieve business goals."},
    {"name": "Introduction to Python Django",
     "description": "Get started with Django, the popular Python web framework. Learn how to build robust, scalable web applications with ease."},
    {"name": "Basics of Cyberlaw",
     "description": "Understand the foundational principles of cyberlaw and its importance in the digital age. Learn how legal frameworks address online activities and protect against cybercrimes."},
    {"name": "E-mail Automation Basics",
     "description": "Discover how to streamline your email marketing with automation. Learn tools and strategies to save time and improve campaign performance."},
    {"name": "How to Create E-books",
     "description": "Learn the steps to create and publish your own e-books. Explore tips on formatting, design, and reaching your target audience."},
    {"name": "Marketing on TikTok",
     "description": "Master the art of creating engaging content for TikTok. Learn marketing strategies that drive brand growth on this dynamic platform."},
    {"name": "Creating Viral Videos",
     "description": "Discover the key elements that make a video go viral. Learn how to craft engaging content that captures attention and encourages sharing."},
    {"name": "Digital Transformation Explained",
     "description": "Understand the concept of digital transformation and its impact on businesses. Learn how to implement technologies that drive innovation and efficiency."},
    {"name": "Basics of Scrum",
     "description": "Get introduced to Scrum, an agile project management framework. Learn how to organize workflows and improve team productivity."},
    {"name": "How to Start a Dropshipping Business",
     "description": "Learn the basics of starting and running a dropshipping business. Explore tools and strategies to source products and manage your online store."},
    {"name": "Virtual Networking Tips",
     "description": "Master the art of building professional connections online. Learn how to leverage platforms like LinkedIn and virtual events effectively."},
    {"name": "The Art of Journaling",
     "description": "Discover how journaling can improve your mental clarity and creativity. Learn techniques to start and maintain a consistent journaling practice."},
    {"name": "Exploring Minimalism",
     "description": "Understand the principles of minimalism and how it can simplify your life. Learn strategies to declutter and focus on what truly matters."},
    {"name": "The Science of Happiness",
     "description": "Explore the psychological and biological foundations of happiness. Learn actionable steps to improve your overall well-being and joy."},
    {"name": "Introduction to Kotlin for Android",
     "description": "Get started with Kotlin, a powerful language for Android development. Learn the basics of building Android apps with clean and concise code."},
    {"name": "Basics of Data Visualization",
     "description": "Learn how to turn raw data into compelling visual stories. Discover tools and techniques for creating charts, graphs, and dashboards."},
    {"name": "Understanding Risk Management",
     "description": "Understand the fundamentals of identifying and managing risks in business. Learn strategies to minimize uncertainties and ensure stability."},
    {"name": "Basics of Quantum Computing",
     "description": "Explore the basics of quantum computing and its revolutionary potential. Learn about qubits, superposition, and how quantum systems differ from classical ones."},
    {"name": "How to Create Better Surveys",
     "description": "Learn how to design surveys that yield valuable insights. Discover techniques to write clear questions and analyze responses effectively."},
    {"name": "Introduction to Personal Finance",
     "description": "Understand the fundamentals of managing your personal finances. Learn how to budget, save, and invest for a secure financial future."},
    {"name": "Basic Yoga Practices",
     "description": "Learn foundational yoga poses and breathing techniques for relaxation and flexibility. Discover how yoga can improve your overall health and well-being."},
    {"name": "Freelance Graphic Design Tips",
     "description": "Master tips for succeeding as a freelance graphic designer. Learn how to find clients, manage projects, and build a strong portfolio."},
    {"name": "Introduction to Machine Learning Libraries",
     "description": "Get introduced to popular machine learning libraries like TensorFlow and scikit-learn. Learn how to implement algorithms and analyze datasets effectively."},
    {"name": "Basics of Content Marketing",
     "description": "Understand the principles of creating and distributing valuable content. Learn strategies to attract and retain your target audience."},
    {"name": "Introduction to Ethical Hacking",
     "description": "Learn the basics of ethical hacking and how to test systems for vulnerabilities. Discover tools and techniques used by cybersecurity professionals."},
    {"name": "How to Use Google Analytics",
     "description": "Discover how to use Google Analytics to track and improve your website's performance. Learn how to analyze traffic, user behavior, and conversion data."},
    {"name": "Basics of Web Hosting",
     "description": "Understand the essentials of web hosting and domain management. Learn how to choose the right hosting service for your website."},
    {"name": "Introduction to App Development",
     "description": "Learn the foundational skills needed to develop your first mobile app. Explore the tools, platforms, and coding languages used in app development."},
    {"name": "Career Development Hacks",
     "description": "Discover strategies to accelerate your career growth and achieve your goals. Learn how to leverage networking, skills development, and goal setting."},
    {"name": "The Future of Marketing",
     "description": "Explore the trends shaping the future of marketing in a digital-first world. Learn how to adapt your strategies to stay ahead of the curve."},
    {"name": "How to Start a Career in Tech",
     "description": "Learn the steps to break into the tech industry and build a successful career. Explore in-demand skills, certifications, and networking strategies."},
    {"name": "Basics of Product Launches",
     "description": "Understand the steps involved in planning and executing a successful product launch. Learn how to create buzz, reach your audience, and track results."},
    {"name": "Mastering Customer Feedback",
     "description": "Learn how to collect, analyze, and act on customer feedback. Discover strategies to improve products and enhance customer satisfaction."},
    {"name": "Introduction to Android Development",
     "description": "Get started with building Android apps from scratch. Learn the basics of Android Studio, Java, and app deployment."}

]
import string
def generate_random_youtube_link():
    # Identyfikator filmu na YouTube ma zwykle 11 znaków.
    video_id = ''.join(random.choices(string.ascii_letters + string.digits, k=11))
    return f"https://www.youtube.com/watch?v={video_id}"

import datetime
from datetime import datetime, timedelta
def generate_random_date():
    # Data początkowa: 1 stycznia 2023
    start_date = datetime(2023, 1, 1)
    # Data końcowa: 31 grudnia 2026
    end_date = datetime(2026, 12, 31)
    # Generowanie losowej liczby dni w przedziale dat
    random_days = random.randint(0, (end_date - start_date).days)
    # Obliczenie losowej daty
    return start_date + timedelta(days=random_days)


import csv


def read_csv_line_by_index(file_name, index):

    with open(file_name, mode='r') as csvfile:
        reader = csv.reader(csvfile)
        rows = list(reader)  # Zamień plik na listę wierszy
        
        if index < 1 or index > len(rows):
            raise ValueError("Indeks poza zakresem. Podaj poprawny numer linii.")
        
        # Pobierz wiersz o podanym indeksie
        specific_row = rows[index - 1]  # Indeksowanie od 0
        if len(specific_row) >= 2:
            return specific_row[0], specific_row[1]  # Zwróć dwie pierwsze kolumny
        else:
            raise ValueError("Linia nie zawiera wystarczających danych.")

def get_description_by_name(webinar_name):
    for webinar in webinars_dec:
        if webinar["name"] == webinar_name:
            return webinar["description"]
    return "Opis nie został znaleziony."

with open('Webinars.csv', mode='w', newline='') as csvfile:
    fieldnames = ['WebinarID','WebinarName','WebinarPrice','VideoLink','WebinarDate',
                  'WebinarDescription','EmployeeID','TranslatorID','LanguageID']
    writer = csv.DictWriter(csvfile,fieldnames=fieldnames)
    
    writer.writeheader()
    print(len(webinar_names))
    # Generuje ID webinaru
    for webID in range(1,201):
        print(webID-1)
        webName = webinar_names[webID-1 if webID-1 < 185 else webID%186+1]
        webPrice = random.randint(5,100)*100
        videoLink = generate_random_youtube_link()
        webinarDate = generate_random_date().strftime("%d-%m-%Y")
        description = get_description_by_name(webName)
        employID = webID % 100 if webID % 100 != 0 else 100
        TranslatorID, LanguageID = read_csv_line_by_index('TranslatorLaunguages.csv', employID)
        
        writer.writerow({
            "WebinarID": webID,
            "WebinarName": webName,
            "WebinarPrice": webPrice,
            "VideoLink": videoLink,
            "WebinarDate": webinarDate,
            "WebinarDescription": description,
            "EmployeeID": employID,
            "TranslatorID": TranslatorID,
            "LanguageID": LanguageID
        })
    
    
    