[project]
name = "pum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "notebook>=7.5.5",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "pot>=0.9.6.post1",
    "scikit-learn>=1.8.0",
    "torch>=2.12.0",
]
